### ISSUE TITLE
Warn when two createStyleSheet are called with the same first argument

### ISSUE THREAD

**Issue by oliviertassinari** [nathanmarks/stylishly#3]
I was wondering how we could improve the dev experience.
What do you think about this warning?

**Comment by nathanmarks** [comment]
Good idea, I was thinking the same thing 👍

**Comment by oliviertassinari** [comment]
:tada: Thanks. I have struggled a bit on this one the first time I used the lib.

**Comment by nathanmarks** [comment]
@oliviertassinari me too! 😄
