### ISSUE TITLE
Server-side rendering, duplicated style

### ISSUE THREAD

**Issue by oliviertassinari** [nathanmarks/stylishly#4]
It seems that the content of the server-side rendered `<style data-stylishly="default">...</style>`
isn't clear at the rendering time, leading to duplicated style in the DOM. Is this intentional?

In my case and in development mode, the server-side-rendered style isn't always in sync with the client-side-rendered style.

**Comment by nathanmarks** [comment]
@oliviertassinari it's not supposed to be cleared, but it also isn't supposed to end up with duplicated styles. I'll have to check this out this weekend.

Can you give any more details as to what not "in sync" involves?
